---
filter_chain_arch: amd64
filter_chain_version: "v0.2.0"
filter_chain_download_url: "https://github.com/hornwind/filter-chain/releases/download/{{ filter_chain_version }}/filter-chain_{{ filter_chain_version | regex_replace('^v','') }}_linux_{{ filter_chain_arch }}.tar.gz"
filter_chain_dir: "/var/lib/filter-chain"

# subnets e.g. "127.0.0.0/8"
filter_chain_networks_allow: []
  # - "127.0.0.0/8"

# country codes e.g. "NL"
filter_chain_countries_allow: []

filter_chain_countries_deny: []

# Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
filter_chain_ripe_refresh: "12h"
